name: "Bug Report"
description: "Report a bug in Shipwright"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: "Thank you for reporting a bug! Please provide as much detail as possible to help us fix it."
  - type: textarea
    id: description
    attributes:
      label: "Describe the bug"
      description: "What happened? What did you expect to happen?"
      placeholder: "Ex: When I run..., it fails with..."
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: "Steps to reproduce"
      description: "How can we reproduce this issue?"
      placeholder: |
        1. Run `shipwright ...`
        2. ...
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: "Expected behavior"
      description: "What should happen instead?"
      placeholder: "Ex: The command should..."
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: "Shipwright version"
      description: "Run `shipwright --version` to find this"
      placeholder: "1.0.0"
    validations:
      required: false
  - type: dropdown
    id: os
    attributes:
      label: "Operating system"
      options:
        - macOS
        - Ubuntu/Debian
        - Other Linux
        - WSL
        - Other
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: "Relevant logs or error output"
      description: "Paste any error messages or logs (use code fences for formatting)"
      render: shell
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: "Additional context"
      description: "Anything else that might help us understand the issue?"
      placeholder: "Ex: This started happening after..."
    validations:
      required: false
