name: "Feature Request"
description: "Suggest a new feature or enhancement"
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: "Thank you for suggesting a feature! Please provide as much detail as possible."
  - type: textarea
    id: description
    attributes:
      label: "Describe the feature"
      description: "What should Shipwright do?"
      placeholder: "Ex: Add support for..."
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: "Use case"
      description: "What problem does this feature solve? Why do you need it?"
      placeholder: "Ex: This would help because..."
    validations:
      required: true
  - type: dropdown
    id: area
    attributes:
      label: "Area"
      description: "Which part of Shipwright is this for?"
      options:
        - Pipeline
        - Daemon
        - Fleet
        - Intelligence
        - Dashboard
        - CLI
        - Memory
        - Templates
        - Cost
        - Other
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: "Additional context"
      description: "Links, screenshots, or other relevant information"
      placeholder: "Ex: Related to issue #123..."
    validations:
      required: false
